Repository ice-craft/ice-craft-FE, pull requests merged in 2024-04, with the labels that each got.

#9 [Feat/#2] - supabase 설정 및 email 로그인
  .prettierrc
  app/_utils/supabase/authAPI.ts
  app/login/page.tsx
  app/register/page.tsx
Labels: ✨Feature

#11 [ADD #8] livekit 설치 및 마피아 페이지 경로 설정
  .vscode/settings.json
  app/_hooks/useQuery.ts
  app/_types/index.ts
  app/layout.tsx
  app/livekitAPI/get-participant-token/route.ts
  app/main/page.tsx
  app/page.tsx
  app/room/[id]/page.tsx
  package.json
  yarn.lock
Labels: 💻 Script, ➕ Add

#13 [Feat/#12] - 이메일 로그인 유효성 조건 설정
  app/_utils/supabase/authAPI.ts
  app/login/page.tsx
Labels: ✨Feature

#15 [Feat] - livekit 모달창 띄우기
  app/_components/AuthButton.tsx
  app/_components/DeployButton.tsx
  app/_components/Header.tsx
  app/_components/NextLogo.tsx
  app/_components/SupabaseLogo.tsx
  app/_components/mafia/Timer.tsx
  app/_components/tutorial/Code.tsx
  app/_components/tutorial/ConnectSupabaseSteps.tsx
  app/_components/tutorial/FetchDataSteps.tsx
  app/_components/tutorial/SignUpUserSteps.tsx
  app/_components/tutorial/Step.tsx
  app/_utils/modal/modal.tsx
  app/_utils/store/modal-store.ts
  app/main/page.tsx
  app/page.tsx
  app/room/[id]/page.tsx
Labels: ✨Feature, 🎨 Style, 📃 Move, ➕ Add

#16 [Feat #4] livekit layout 생성
  .vscode/settings.json
  app/layout.tsx
  app/room/[id]/page.tsx
Labels: ✨Feature, 🎨 Style

#19 [Feat/#14] - sns를 통해 로그인
  app/_utils/supabase/accountAPI.ts
  app/_utils/supabase/authAPI.ts
  app/login/page.tsx
  app/login/submit-button.tsx
  app/main/page.tsx
  app/test/page.tsx
  next.config.js
Labels: ✨Feature

#22 [Test #20] 테스트 주석 추가
  app/room/[id]/page.tsx
Labels: ➕ Add

#24 [Style/#23] - 회원가입 페이지 레이아웃 구현
  app/register/page.tsx
Labels: 🎨 Style

#26 [Feat/25] - 회원가입 기능 추가
  app/_components/register/InputMessage.tsx
  app/_utils/supabase/authAPI.ts
  app/login/page.tsx
  app/register/page.tsx
Labels: ✨Feature

#28 [Feat] intropage layout 생성, 비디오 추가
  app/_components/intro/Intropage.tsx
  app/_style/HeaderLogo.ts
  app/_style/Intropage/video.module.css
  app/_style/test.ts
  app/page.tsx
Labels: ✨Feature, 🎨 Style

#29 [Feat/#27] - mafia 방 supabse 테이블 작업 및 supabase api 구현
  app/_utils/supabase/roomAPI.ts
  app/test2/page.tsx
Labels: ✨Feature

#30 [Feat #7] 플레이어의 캠 및 오디오 설정 제어
  app/protected/page.tsx
  app/room/[id]/page.tsx
Labels: ✨Feature

#31 [feat/#6] 캠 이미지 토글 구현
  app/_style/videoOverlay.css
  app/room/[id]/page.tsx
Labels: ✨Feature

#43 [Feat #42] 메인페이지 레이아웃
  .vscode/settings.json
  app/_components/layout/Footer.tsx
  app/_components/layout/Header.tsx
  app/_components/layout/Nav.tsx
  app/_components/mainpageComponents/Roombutton.tsx
  app/_style/commons/commons.module.css
  app/layout.tsx
  app/main/page.tsx
  app/page.tsx
  app/ranking/page.tsx
  public/images/footer_logo.svg
  public/images/logo.svg
  public/images/test.ts
Labels: ✨Feature

#44 1차 코드 리뷰 관련 리펙토링
  .vscode/settings.json
  app/_api/liveKitApi.ts
  app/_api/test.ts
  app/_components/mafia/Timer.tsx
  app/_hooks/test.ts
  app/_hooks/useQuery.ts
  app/_hooks/useToken.ts
  app/_store/modal-store.ts
  app/_types/index.ts
  app/livekit/get-participant-token/route.ts
  app/protected/page.tsx
  app/room/[id]/page.tsx
Labels: ✍️ Refactor

#46 [Feat #42] - 메인페이지 layout 생성
  app/_style/mainPage/main.module.css
  app/main/page.tsx
  public/images/mafia_item.png
  public/images/mafia_visual.png
Labels: ✨Feature, 🎨 Style

#50 [Pull #17] 병합완료
  app/_components/intro/Intropage.tsx
  package.json
  yarn.lock
Labels: ✨Feature

#54 [Fix #47] room 페이지의 layout 구성 및 컴포넌트 분리
  app/_components/mafia/MyVideoConference.tsx
  app/room/[id]/page.tsx
  app/room/layout.tsx
Labels: 🔨 Fix

#55 [Style] 메인페이지 수정, intro페이지 추가
  .vscode/settings.json
  app/_components/intro/Intropage.tsx
  app/_components/layout/Footer.tsx
  app/_components/layout/Header.tsx
  app/_style/Intropage/video.module.css
  app/_style/commons/commons.module.css
  app/_style/introPage/intro.module.css
  app/_style/mainPage/main.module.css
  app/layout.tsx
  app/main/page.tsx
  app/page.tsx
  metadata.ts
Labels: 🎨 Style, 🔨 Fix

#56 [Feat #49] utils textTyping 추가, top button 로직 추가
  app/_style/introPage/intro.module.css
  app/_utils/GoTopButton.tsx
  app/_utils/TextTyping.tsx
  app/layout.tsx
Labels: 🐞bugFix, ✨Feature

#60 [Feat #33] 카운트 다운 커스텀 훅 구현
  app/_components/mafia/MafiaModal.tsx
  app/_components/mafia/Timer.tsx
  app/_hooks/useCountDown.ts
  app/_style/mafiaRoom/overlay.module.css
  app/room/[id]/page.tsx
Labels: ✨Feature

#62 [Style #48] 마피아 게임 로직 이미지 추가, header,footer,main 반응형 추가
  app/_style/commons/commons.module.css
  app/_style/mainPage/main.module.css
  public/images/Citizens_Card.png
  public/images/Doctor_Card.png
  public/images/Mafia_Card.png
  public/images/Police_Card.png
  public/images/cam_check.png
  public/images/cam_citizen.png
  public/images/cam_doctor.png
  public/images/cam_mafia.png
  public/images/cam_police.png
  public/images/citizens_ToolTip_Icon.png
  public/images/doctor_ToolTip_Icon.png
  public/images/mafia_ToolTip_Icon.png
  public/images/police_ToolTip_Icon.png
Labels: 🎨 Style

#65 [Feat #63] 마피아페이지 레이아웃 컴포넌트 분리 작업 완료
  .vscode/settings.json
  app/_components/mafia/LocalParticipant.tsx
  app/_components/mafia/MafiaModal.tsx
  app/_components/mafia/MafiaNickName.tsx
  app/_components/mafia/MyVideoConference.tsx
  app/_components/mafia/RemoteParticipant.tsx
  app/_store/modal-store.ts
  app/_store/overlay-store.ts
  app/_store/video-store.ts
  app/_style/HeaderLogo.ts
  app/_style/commons/commons.module.css
  app/_style/livekit/livekit.module.css
  app/_style/mainPage/main.module.css
  app/_style/modal/modal.module.css
  app/_types/index.ts
  app/_utils/modal/modal.tsx
  app/main/page.tsx
  app/page.tsx
  app/room/layout.tsx
  public/images/mafia_visual.png
Labels: ✍️ Refactor, ✨Feature, 🎨 Style, 🔨 Fix

#66 [Feat/#32] - 마피아 알고리즘 구현
  app/_utils/mafia-algorithm/class/citizenClass.js
  app/_utils/mafia-algorithm/class/doctorClass.js
  app/_utils/mafia-algorithm/class/mafiaClass.js
  app/_utils/mafia-algorithm/class/moderatorClass.js
  app/_utils/mafia-algorithm/class/policeClass.js
  app/_utils/mafia-algorithm/gamePlay.js
  app/_utils/mafia-algorithm/play-variable.js
Labels: ✨Feature, ➕ Add

#69 [Add/#68] - 채팅 기능에 필요한 패키지 설치 및 초기 설정
  app/_utils/socket/socket.js
  app/chat_client/page.tsx
  package.json
  yarn.lock
Labels: ✨Feature, 💻 Script, ➕ Add

#74 [Feat #67] 이미지 토글 버튼 구현
  app/_components/mafia/LocalParticipant.tsx
  app/_components/mafia/MafiaToolTip.tsx
  app/_components/mafia/MyVideoConference.tsx
  app/_components/mafia/RemoteParticipant.tsx
  app/_store/overlay-store.ts
  app/_style/livekit/livekit.module.css
  app/_types/index.ts
  app/room/layout.tsx
  public/images/citizens_ToolTip_text.png
  public/images/doctor_ToolTip_text.png
  public/images/mafia_ToolTip_text.png
  public/images/police_ToolTip_text.png
Labels: ✨Feature

#79 [Feat #40] 방만들기 모달, 방생성
  .vscode/settings.json
  app/_components/mainpageComponents/MainCreateRoom.tsx
  app/_components/mainpageComponents/Roombutton.tsx
  app/_utils/modal/modal.tsx
  app/main/page.tsx
Labels: ✨Feature

#81 [Feat] timer 커스텀 훅 구현
  app/_components/mafia/LocalParticipant.tsx
  app/_components/mafia/MafiaModal.tsx
  app/_components/mafia/MyVideoConference.tsx
  app/_hooks/useCountUp.ts
  app/_store/count-store.ts
  app/_store/video-store.ts
  app/_types/index.ts
  app/_utils/participantCamSettings/camSetting.ts
  app/room/[id]/page.tsx
Labels: 🐞bugFix, ✨Feature

#85 [Move] 파일구조변경
  api/liveKitApi.ts
  app/(withGlobalLayout)/callback/route.ts
  app/(withGlobalLayout)/chat_client/page.tsx
  app/(withGlobalLayout)/layout.tsx
  app/(withGlobalLayout)/login/page.tsx
  app/(withGlobalLayout)/main/page.tsx
  app/(withGlobalLayout)/register/page.tsx
  app/(withoutGlobalLayout)/page.tsx
  app/(withoutGlobalLayout)/room/[id]/page.tsx
  app/(withoutGlobalLayout)/room/layout.tsx
  app/livekit/get-participant-token/route.ts
  app/test/page.tsx
  app/test2/page.tsx
  components/layout/Footer.tsx
  components/layout/Header.tsx
  components/layout/Nav.tsx
  components/mafia/LocalParticipant.tsx
  components/mafia/MafiaModal.tsx
  components/mafia/MafiaNickName.tsx
  components/mafia/MafiaToolTip.tsx
  components/mafia/MyVideoConference.tsx
  components/mafia/RemoteParticipant.tsx
  components/mainpageComponents/MainCreateRoom.tsx
  components/mainpageComponents/Roombutton.tsx
  components/register/InputMessage.tsx
  hooks/useCountDown.ts
  hooks/useCountUp.ts
  hooks/useToken.ts
  middleware.ts
  store/count-store.ts
  store/modal-store.ts
  store/overlay-store.ts
  style/Intropage/intro.module.css
  style/commons/commons.module.css
  style/livekit/livekit.module.css
  style/mainPage/main.module.css
  style/modal/modal.module.css
  types/index.ts
  utils/GoTopButton.tsx
  utils/TextTyping.tsx
  utils/mafia-algorithm/class/citizenClass.js
  utils/mafia-algorithm/class/doctorClass.js
  utils/mafia-algorithm/class/mafiaClass.js
  utils/mafia-algorithm/class/moderatorClass.js
  utils/mafia-algorithm/class/policeClass.js
  utils/mafia-algorithm/gamePlay.js
  utils/mafia-algorithm/play-variable.js
  utils/modal/modal.tsx
  utils/participantCamSettings/camSetting.ts
  utils/socket/socket.js
  utils/supabase/accountAPI.ts
  utils/supabase/authAPI.ts
  utils/supabase/client.ts
  utils/supabase/middleware.ts
  utils/supabase/roomAPI.ts
  utils/supabase/server.ts
Labels: 📃 Move

#87 [Feat #75] 마이크 및 캠 설정
  app/(withoutGlobalLayout)/room/layout.tsx
  components/mafia/Setting.tsx
Labels: ✨Feature

#92 [Feat #77] 직업 카드창 모달 띄우기 기능 구현
  app/(withGlobalLayout)/main/page.tsx
  app/(withoutGlobalLayout)/page.tsx
  components/mafia/UserWorkModal.tsx
  style/livekit/livekit.module.css
  style/modal/modal.module.css
Labels: ✨Feature

#95 [Style #89] 전체페이지 css 점검
  .vscode/settings.json
  app/(withGlobalLayout)/login/page.tsx
  app/(withGlobalLayout)/register/page.tsx
  app/(withoutGlobalLayout)/page.tsx
  app/globals.css
  app/not-found.tsx
  components/mafia/LocalParticipant.tsx
  components/mainpageComponents/MainCreateRoom.tsx
  components/register/InputMessage.tsx
  package.json
  public/images/bg.png
  public/images/clear.png
  public/images/game_choice_mafia.png
  public/images/game_choice_mafia_active.png
  public/images/game_choice_song.png
  public/images/game_choice_song_active.png
  public/images/join_facebook.png
  public/images/join_github.png
  public/images/join_google.png
  public/images/join_kakaotalk.png
  style/Intropage/intro.module.css
  style/commons/commons.module.css
  style/livekit/livekit.module.css
  style/login/login.module.css
  style/mainPage/main.module.css
  style/modal/modal.module.css
  style/register/register.module.css
  yarn.lock
Labels: 🎨 Style, 🔨 Fix

#99 [Fix #98] 에러 처리 변경
  app/(withoutGlobalLayout)/room/layout.tsx
Labels: 🔨 Fix

#101 [Refactor#90] - 1차 코드 리뷰 리팩토링
  app/(withGlobalLayout)/login/page.tsx
  app/(withGlobalLayout)/register/page.tsx
  components/register/InputMessage.tsx
  components/register/RegisterButton.tsx
  style/register/register.module.css
  types/supabase.ts
  utils/supabase/accountAPI.ts
  utils/supabase/authAPI.ts
  utils/supabase/client.ts
  utils/supabase/roomAPI.ts
Labels: ✍️ Refactor

#104 [Refactor #100] 1차 코드 리뷰_리팩토링_최종본
  api/liveKitApi.ts
Labels: ✍️ Refactor

#106 [Fix] 캠 및 오디오 수정 완료
  app/(withoutGlobalLayout)/room/[id]/page.tsx
  app/(withoutGlobalLayout)/room/layout.tsx
  components/mafia/LocalParticipant.tsx
  components/mafia/MyVideoConference.tsx
  store/leave-store.ts
  utils/participantCamSettings/camSetting.ts
Labels: 🐞bugFix, ✨Feature, 🔨 Fix

#109 [Move] assets 폴더 위치 변경
  app/(withGlobalLayout)/main/page.tsx
  app/(withoutGlobalLayout)/login/page.tsx
  app/(withoutGlobalLayout)/page.tsx
  app/(withoutGlobalLayout)/register/page.tsx
  assets/images/Citizens_Card.png
  assets/images/Doctor_Card.png
  assets/images/Mafia_Card.png
  assets/images/Police_Card.png
  assets/images/bg.png
  assets/images/cam_check.png
  assets/images/cam_citizen.png
  assets/images/cam_doctor.png
  assets/images/cam_mafia.png
  assets/images/cam_police.png
  assets/images/citizens_ToolTip_Icon.png
  assets/images/citizens_ToolTip_text.png
  assets/images/clear.png
  assets/images/doctor_ToolTip_Icon.png
  assets/images/doctor_ToolTip_text.png
  assets/images/footer_logo.svg
  assets/images/game_choice_mafia.png
  assets/images/game_choice_mafia_active.png
  assets/images/game_choice_song.png
  assets/images/game_choice_song_active.png
  assets/images/icon-github.png
  assets/images/icon_person.png
  assets/images/icon_plus.png
  assets/images/icon_point.png
  assets/images/icon_search.png
  assets/images/join_facebook.svg
  assets/images/join_github.svg
  assets/images/join_google.svg
  assets/images/join_kakaotalk.svg
  assets/images/logo.svg
  assets/images/mafia_ToolTip_Icon.png
  assets/images/mafia_ToolTip_text.png
  assets/images/mafia_game_title.svg
  assets/images/mafia_item.png
  assets/images/mafia_visual.png
  assets/images/police_ToolTip_Icon.png
  assets/images/police_ToolTip_text.png
  components/layout/Footer.tsx
  components/layout/Header.tsx
  components/mafia/LocalParticipant.tsx
  components/mafia/MafiaToolTip.tsx
  components/mafia/RemoteParticipant.tsx
  components/mafia/UserWorkModal.tsx
  components/mainpageComponents/MainCreateRoom.tsx
  style/login/login.module.css
  style/mainPage/main.module.css
  style/register/register.module.css
Labels: 📃 Move

#110 캠 클릭시 투표창 활성화 및 비활성화 기능 구현
  app/(withoutGlobalLayout)/room/[id]/page.tsx
  components/mafia/LocalParticipant.tsx
  components/mafia/RemoteParticipant.tsx
  store/leave-store.ts
  store/overlay-store.ts
  style/livekit/livekit.module.css
  types/index.ts
Labels: ✨Feature

#112 [Feat #38] 리스트뿌리기까지
  .vscode/settings.json
  app/(withGlobalLayout)/main/page.tsx
  app/(withoutGlobalLayout)/room/[id]/page.tsx
  components/mainpageComponents/MainCreateRoom.tsx
Labels: ✨Feature, 🔨 Fix

#114 [Feat] progress bar 구현
  components/mafia/MafiaModal.tsx
  style/modal/modal.module.css
Labels: ✨Feature

#116 [Feat #96] - 마피아 모달창 조건부 랜더링 추가
  app/(withoutGlobalLayout)/room/[id]/page.tsx
  components/mafia/CheckModal.tsx
  components/mafia/MafiaModal.tsx
  components/mafia/MyVideoConference.tsx
  components/mafia/UserWorkModal.tsx
  hooks/useCountDown.ts
  store/active-store.ts
  style/mainPage/main.module.css
  style/modal/modal.module.css
  types/index.ts
Labels: ✨Feature, 🎨 Style

#118 [Feat] 캠 클릭 시 조건부 이미지 활성화
  components/mafia/LocalParticipant.tsx
  components/mafia/MyVideoConference.tsx
  components/mafia/RemoteParticipant.tsx
  components/mainpageComponents/MainCreateRoom.tsx
  store/image-store.ts
  types/index.ts
Labels: ✨Feature

#119 [Feat/#103] - 텍스트 기반 마피아 게임 구현
  app/(withGlobalLayout)/mafia_play/page.tsx
  utils/supabase/roomAPI.ts
Labels: ✨Feature

#121 [Feat #120] - 마피아 게임에 필요한 기능 구현
  app/(withGlobalLayout)/mafia_play/page.tsx
Labels: ✨Feature

#122 [Feat #113] 임시 커밋
  app/(withGlobalLayout)/main/page.tsx
  app/test2/page.tsx
  components/mainpageComponents/MainCreateRoom.tsx
Labels: ✨Feature

#126 [Test] socket IO 사용
  app/(withoutGlobalLayout)/room/[id]/page.tsx
Labels: ✅ Test

#127 [Feat #117] 마피아 게임 로직 입히기(1)
  app/(withGlobalLayout)/mafia_play/page.tsx
  components/mafia/CheckModal.tsx
  components/mafia/MafiaModal.tsx
  components/mafia/MafiaToolTip.tsx
  components/mafia/MyVideoConference.tsx
  components/mafia/UserWorkModal.tsx
  store/connect-store.ts
  types/index.ts
Labels: ✨Feature

#130 [Fix #129] 3차 리팩토링 완료
  app/(withoutGlobalLayout)/room/layout.tsx
  components/layout/Footer.tsx
Labels: 🔨 Fix

#135 [Refactor #134] - 튜터님 코드 리뷰 사항 반영
  app/(withoutGlobalLayout)/login/page.tsx
  app/(withoutGlobalLayout)/register/page.tsx
  components/logIn/ErrorMessage.tsx
Labels: ✍️ Refactor

#137 마피아 방 입장 기능 구현 및 파일 구조 및 코드 수정
  api/liveKitApi.ts
  app/(withGlobalLayout)/main/page.tsx
  app/(withoutGlobalLayout)/room/[id]/page.tsx
  app/(withoutGlobalLayout)/room/layout.tsx
  app/livekit/get-participant-token/route.ts
  components/mafia/MafiaPlayRooms.tsx
  components/mainpageComponents/MainCreateRoom.tsx
  hooks/useToken.ts
  store/toggle-store.ts
  types/index.ts
Labels: ✨Feature, 🗑️ DELETE, 🔨 Fix

#138 [Feat #132] 빠른입장
  app/(withGlobalLayout)/main/page.tsx
Labels: ✨Feature, 🔨 Fix

#141 [Refactor/#136] - 백엔드 서버 구조 변경 전 리팩토링
  app/(withGlobalLayout)/mafia_play/page.tsx
  utils/supabase/authAPI.ts
Labels: ✍️ Refactor

#143 [Feat #128] - 마피아 로직 입히기(게임시작 버튼)
  app/(withoutGlobalLayout)/page.tsx
  app/globals.css
  assets/images/bg.avif
  assets/images/bg.png
  assets/images/intro_bg.avif
  assets/images/intro_bg.png
  assets/images/mafia_game_title.svg
  assets/images/mafia_visual.avif
  assets/images/mafia_visual.png
  components/mafia/LocalParticipant.tsx
  public/fonts/Pretendard-Bold.woff
  public/fonts/Pretendard-Regular.woff
  public/fonts/fonts.ts
  store/toggle-store.ts
  style/livekit/livekit.module.css
  style/login/login.module.css
  style/mainPage/main.module.css
  style/modal/modal.module.css
  style/register/register.module.css
  types/index.ts
Labels: ✨Feature, 🎨 Style

#151 일반 입장, 빠른입장, 방만들기 수정
  app/(withGlobalLayout)/main/page.tsx
  app/(withoutGlobalLayout)/room/[id]/page.tsx
  components/mafia/LocalParticipant.tsx
  components/mafia/MafiaPlayRooms.tsx
  components/mainpageComponents/MainCreateRoom.tsx
  hooks/useGetRooms.ts
  hooks/useToken.ts
Labels: ✨Feature, 🔨 Fix

#156 [Feat #144] - 공용 모달창 수정
  components/mafia/GroupMafiaModal.tsx
  components/mafia/LocalParticipant.tsx
  components/mafia/MafiaModal.tsx
  hooks/useModal.ts
  style/mainPage/main.module.css
  types/index.ts
Labels: ✨Feature

#160 [Refactor #155] 사용자 직업카드 간결하게 정리
  components/mafia/RenderCards.tsx
Labels: ✍️ Refactor

#163 [Feat #154] 마피아 게임 페이지 - 사용자가 ready 버튼 클릭시 캠 위 이미지 체크 표시 추가
  components/mafia/LocalParticipant.tsx
  components/mafia/RemoteParticipant.tsx
  store/image-store.ts
  style/livekit/livekit.module.css
  types/index.ts
Labels: ✨Feature

#164 방 리스트 및 GameStart 버튼 기능 구현
  app/(withGlobalLayout)/main/page.tsx
  app/(withoutGlobalLayout)/room/[id]/page.tsx
  app/layout.tsx
  components/mafia/JoinMafiaRoom.tsx
  components/mafia/Loading.tsx
  components/mafia/MafiaPlayRooms.tsx
  components/mainpageComponents/MainCreateRoom.tsx
  store/exit-store.ts
  types/index.ts
Labels: ✨Feature, 🔨 Fix

#167 [Refactor #157] 마피아 게임 페이지 서버 연결 전 로직 확인
  components/mafia/GroupMafiaModal.tsx
  components/mafia/MafiaPlayRooms.tsx
Labels: ✍️ Refactor

#168 [Fix #149] png이미지 avif로 수정 build 오류 수정
  assets/images/Citizens_Card.avif
  assets/images/Citizens_Card.png
  assets/images/Doctor_Card.avif
  assets/images/Doctor_Card.png
  assets/images/Mafia_Card.avif
  assets/images/Mafia_Card.png
  assets/images/Police_Card.avif
  assets/images/Police_Card.png
  components/mafia/LocalParticipant.tsx
  components/mafia/UserRoleModal.tsx
  types/index.ts
Labels: 🔨 Fix

#169 [Feat #59] 메인페이지 goTopButton 함수 추가
  app/(withGlobalLayout)/main/page.tsx
  assets/images/arrow_top.svg
  style/commons/commons.module.css
  utils/GoTopButton.tsx
Labels: ✨Feature

#171 [Feat #145] 메인페이지 방 입장 아무도 없을시 비어있다는 로직 이미지 추가
  app/(withGlobalLayout)/main/page.tsx
  assets/images/visit_empty.svg
  style/mainPage/main.module.css
Labels: ✨Feature

#174 [Style #170] 메인페이지로 이동시 로딩 애니메이션 추가
  assets/images/visit_empty.svg
  components/mafia/Loading.tsx
  style/commons/commons.module.css
Labels: 🎨 Style

#175 [Feat #146] 메인페이지 검색기능 구현
  app/(withGlobalLayout)/main/page.tsx
Labels: ✨Feature

#176 [Feat #173] Info Page 생성 후 작업 완료
  .vscode/settings.json
  app/(withGlobalLayout)/mafiainfo/page.tsx
  app/(withGlobalLayout)/main/page.tsx
  assets/images/citizen_victory.svg
  assets/images/mafia_info_choosing.svg
  assets/images/mafia_info_citizen.svg
  assets/images/mafia_info_doctor.svg
  assets/images/mafia_info_final.svg
  assets/images/mafia_info_mafia.svg
  assets/images/mafia_info_morning.svg
  assets/images/mafia_info_police.svg
  assets/images/mafia_info_start.svg
  assets/images/mafia_info_title.svg
  assets/images/mafia_info_vote.svg
  assets/images/mafia_victory.svg
  style/mafiaInfo/mafiaInfo.module.css
  style/mainPage/main.module.css
Labels: ✨Feature, 🎨 Style, ➕ Add

#177 [Feat #172] 랭킹페이지 추가
  app/(withGlobalLayout)/ranking/page.tsx
  assets/images/ranking_1.svg
  assets/images/ranking_2.svg
  assets/images/ranking_3.svg
  assets/images/ranking_arrow_left.svg
  assets/images/ranking_arrow_right.svg
  assets/images/ranking_empty.svg
  style/ranking/ranking.module.css
Labels: ✨Feature, 🎨 Style

#178 캠 클릭시 조건에 따른 이미지 띄우기
  app/(withGlobalLayout)/main/page.tsx
  app/livekit/get-participant-token/route.ts
  components/mafia/LocalParticipant.tsx
  components/mafia/MafiaPlayRooms.tsx
  components/mafia/RemoteParticipant.tsx
  store/overlay-store.ts
  types/index.ts
Labels: 🔨 Fix

#181 [Feat #179] 헤더 로그인,로그아웃 기능 추가
  components/layout/Nav.tsx
Labels: ✨Feature

#183 [Feat #182] 전체 페이지의 조건에 따른 URL 직접 접근 방지
  app/(withGlobalLayout)/main/page.tsx
  app/(withoutGlobalLayout)/login/page.tsx
  app/(withoutGlobalLayout)/page.tsx
  components/mainpageComponents/MainCreateRoom.tsx
  middleware.ts
  next.config.js
  utils/supabase/client.ts
  utils/supabase/middleware.ts
  utils/supabase/server.ts
Labels: ✨Feature

#184 [Refactor #150] 코드 구조 변경
  app/(withGlobalLayout)/mafia_play/page.tsx
  types/supabase.ts
  utils/supabase/statusAPI.ts
Labels: ✍️ Refactor

#185 [Feat #180] 랭킹데이터 편집
  app/(withGlobalLayout)/ranking/page.tsx
  types/supabase.ts
Labels: ✨Feature

#188 [Fix #187] 파비콘 이미지 추가, 메인페이지,랭킹페이지 search icon변경
  app/(withGlobalLayout)/main/page.tsx
  app/(withGlobalLayout)/ranking/page.tsx
  app/favicon.ico
  style/mainPage/main.module.css
  style/ranking/ranking.module.css
Labels: 🎨 Style, 🔨 Fix

#193 Test 임시 로그인으로 변경 및 오디오 끄기
  api/liveKitApi.ts
  app/(withGlobalLayout)/main/page.tsx
  components/mafia/MafiaPlayRooms.tsx
Labels: ✅ Test

#195 [Feat #194] 게임 준비 완)
  api/liveKitApi.ts
  components/mafia/JoinMafiaRoom.tsx
  components/mafia/LocalParticipant.tsx
  components/mafia/RemoteParticipant.tsx
  hooks/useToken.ts
Labels: ✨Feature, ✅ Test

#200 [Fix #199] 로그인, 회원가입 시 메인페이지 이동
  app/(withoutGlobalLayout)/login/page.tsx
  app/(withoutGlobalLayout)/register/page.tsx
Labels: 🔨 Fix

#206 [Fix #189] ISR 삽입
  app/(withGlobalLayout)/ranking/page.tsx
Labels: 🔨 Fix

#209 [Fix #208] 회원가입 버튼 오류 수정
  app/(withoutGlobalLayout)/register/page.tsx
Labels: 🔨 Fix

#210 socket server와 연동 및 타이머 수정
  app/(withGlobalLayout)/mafia_play/page.tsx
  app/(withGlobalLayout)/main/page.tsx
  components/mafia/CheckModal.tsx
  components/mafia/GroupMafiaModal.tsx
  components/mafia/JoinMafiaRoom.tsx
  components/mafia/LocalParticipant.tsx
  components/mafia/MafiaPlayRooms.tsx
  components/mainpageComponents/MainCreateRoom.tsx
  hooks/useCountDown.ts
  hooks/useCountUp.ts
  store/showModal.store.ts
  store/toggle-store.ts
  types/index.ts
Labels: ✨Feature

#212 마피아 시간의 모달창 띄우기 및 마피아 user의 카메라 세팅
  components/mafia/GroupMafiaModal.tsx
  components/mafia/JoinMafiaRoom.tsx
  components/mafia/MafiaPlayRooms.tsx
  types/index.ts
  utils/mafiaSocket/mafiaSocket.ts
Labels: ✨Feature

#213 [Fix #201] - 서버 및 클라이언트 게임 로직 수정
  app/(withGlobalLayout)/mafia_play/page.tsx
Labels: 🔨 Fix

#219 [Fix #214] - 서버 및 클라이언트 에러 및 예외 사항 처리
  app/(withGlobalLayout)/mafia_play/page.tsx
Labels: 🔨 Fix

#221 [Feat #220] 기존 클라이언트에서 만든 투표 로직을 서버 로직과 연동
  app/(withGlobalLayout)/mafia_play/page.tsx
  components/mafia/GroupMafiaModal.tsx
  components/mafia/JoinMafiaRoom.tsx
  components/mafia/LocalParticipant.tsx
  components/mafia/MafiaPlayRooms.tsx
  types/index.ts
  utils/mafiaSocket/mafiaSocket.ts
  utils/participantCamSettings/camSetting.ts
  utils/supabase/statusAPI.ts
Labels: ✨Feature, 🔨 Fix

#224 투표 시간 및 투표 결과를 서버와 연결
  components/mafia/MafiaPlayRooms.tsx
  types/index.ts
  utils/mafiaSocket/mafiaSocket.ts
Labels: 🔨 Fix

#226 [Fix #222] 마피아 게임 플레이 서버와 클라이언트, 데이터베이스 부분 수정
  app/(withGlobalLayout)/mafia_play/page.tsx
Labels: 🔨 Fix

#228 [Feat #218] 마피아 게임페이지 사용자 이미지 모달 추가
  components/mafia/GroupMafiaModal.tsx
  components/mafia/MafiaPlayRooms.tsx
  components/mafia/UserRoleModal.tsx
Labels: ✨Feature

#229 [Fix #227] 메타데이터 삽입
  app/layout.tsx
Labels: 🔨 Fix
