Repository ice-craft/ice-craft-FE, pull requests merged in 2024-06, with the labels that each got.

#259 투표 기능 및 결과 모달창 구현 완료
  components/mafia/GameStartButton.tsx
  components/mafia/JoinMafiaRoom.tsx
  components/mafia/LocalParticipant.tsx
  components/mafia/MafiaPlayRooms.tsx
  components/mafia/MafiaToolTip.tsx
  components/mafia/MyParticipantTile.tsx
  components/mafia/RemoteParticipant.tsx
  components/mafia/SpeakTimer.tsx
  components/modal/CheckModal.tsx
  components/modal/GroupMafiaModal.tsx
  components/modal/UserRoleModal.tsx
  components/modal/VoteResultModal.tsx
  hooks/useMediaSocket.ts
  hooks/useModalSocket.ts
  hooks/useSocketOff.ts
  hooks/useSocketOn.ts
  store/active-store.ts
  store/count-store.ts
  store/overlay-store.ts
  store/show-modal-store.ts
  tsconfig.json
  types/index.ts
Labels: ✨Feature, 🔨 Fix

#261 투표 기능 및 결과 모달창 기능 구현 완료
  components/mafia/MafiaPlayRooms.tsx
  components/mafia/MafiaToolTip.tsx
  components/mafia/RemoteParticipant.tsx
  components/mafia/SpeakTimer.tsx
  components/modal/CheckModal.tsx
  components/modal/GroupMafiaModal.tsx
  components/modal/ModalProgress.tsx
  components/modal/VoteResultModal.tsx
  hooks/useCountDown.ts
  hooks/useModalSocket.ts
  store/count-store.ts
  store/image-store.ts
  store/overlay-store.ts
  store/show-modal-store.ts
  types/index.ts
  utils/mafiaSocket/getPlayerJob.ts
Labels: ✨Feature, 🔨 Fix

#264 죽은 player 미디어 처리 및 클릭 이벤트 비활성화
  components/mafia/GameStartButton.tsx
  components/mafia/JoinMafiaRoom.tsx
  components/mafia/LocalParticipant.tsx
  components/mafia/MafiaPlayRooms.tsx
  components/mafia/MyParticipantTile.tsx
  components/mafia/RemoteParticipant.tsx
  components/mafia/SpeakTimer.tsx
  components/modal/CheckModal.tsx
  components/modal/UserRoleModal.tsx
  components/modal/VoteResultModal.tsx
  hooks/useCountDown.ts
  hooks/useMediaSocket.ts
  hooks/useModalSocket.ts
  hooks/useSelectSocket.ts
  store/active-store.ts
  store/game-store.ts
  store/show-modal-store.ts
  store/toggle-store.ts
  types/index.ts
  utils/mafiaSocket/getPlayerJob.ts
Labels: ✨Feature, 🔨 Fix

#266 [Fix #239] 서버 및 클라이언트 구조 변경
  app/(withGlobalLayout)/mafia_play/page.tsx
  package-lock.json
  package.json
  yarn.lock
Labels: 🔨 Fix

#269 [Feat #267] - 마피아 게임페이지 죽은 유저 처리 이미지추가 + 컴포넌트 분리 작업
  assets/images/player_die.svg
  components/mafia/LocalParticipant.tsx
  components/mafia/MafiaPlayRooms.tsx
  components/mafia/MyParticipantTile.tsx
  components/mafia/RemoteParticipant.tsx
  style/livekit/livekit.module.css
  types/index.ts
Labels: ✨Feature

#275 [Feat #265] - 마피아 게임 페이지 최후의 투표 모달 , 승리 모달 소켓 연결
  components/mafia/LocalParticipant.tsx
  components/mafia/MafiaToolTip.tsx
  components/mafia/MyParticipantTile.tsx
  components/mafia/RemoteParticipant.tsx
  components/mafia/RemoteParticipantTile.tsx
  components/mafia/RenderCards.tsx
  components/modal/CheckModal.tsx
  components/modal/UserRoleModal.tsx
  components/modal/VictoryModal.tsx
  hooks/useClickHandler.ts
  hooks/useModalSocket.ts
  types/index.ts
  yarn.lock
Labels: ✍️ Refactor, ✨Feature

#278 [Feat #277] - 메인페이지 노래맞추기 게임 visual영역 슬라이드 추가, 버튼 추가
  .vscode/settings.json
  app/(withGlobalLayout)/main/page.tsx
  assets/images/song_game_title.svg
  assets/images/song_visual.avif
  package-lock.json
  package.json
  style/mainPage/main.module.css
  style/mainPage/swiper.css
  yarn.lock
Labels: ✨Feature, 💻 Script

#280 [Feat #276] - 메인페이지 방 만들기 모달창 수정
  app/(withGlobalLayout)/main/page.tsx
  assets/images/song_game_title 2.svg
  assets/images/song_game_title.svg
  components/mafia/MafiaModals.tsx
  components/mafia/MafiaPlayRooms.tsx
  components/modal/CreateRoomModal.tsx
  style/mainPage/main.module.css
  style/mainPage/swiper.css
Labels: ✨Feature, 🔨 Fix

#282 [Feat #279] 게임 준비 및 게임 시작 socket 연결
  components/mafia/GameStartButton.tsx
  components/mafia/MafiaPlayRooms.tsx
  components/mafia/RemoteParticipantTile.tsx
  hooks/useSelectSocket.ts
  yarn.lock
Labels: ✨Feature, 🔨 Fix

#288 [Feat #283] players의 초기 Ready 상태에 대한 socket Event 연결
  app/(withoutGlobalLayout)/room/[id]/page.tsx
  app/livekit/get-participant-token/route.ts
  components/layout/Loading.tsx
  components/mafia/GameStartButton.tsx
  components/mafia/JoinMafiaRoom.tsx
  components/mafia/LocalParticipant.tsx
  components/mafia/MafiaPlayRooms.tsx
  components/mafia/RemoteParticipant.tsx
  components/mafia/RemoteParticipantTile.tsx
  components/mafia/SpeakTimer.tsx
  hooks/useMediaSocket.ts
  hooks/useModalSocket.ts
  store/game-store.ts
  store/image-store.ts
  store/overlay-store.ts
  store/show-modal-store.ts
  types/index.ts
Labels: 🐞bugFix, ✨Feature

#289 [Refactor #285] - 메인페이지 리팩토링, skeleton라이브러리 추가
  app/(withGlobalLayout)/main/page.tsx
  components/mafia/LocalParticipant.tsx
  components/mafia/RemoteParticipant.tsx
  components/main/MainSkeleton.tsx
  components/main/MainVisual.tsx
  components/main/RoomListItem.tsx
  components/modal/VictoryModal.tsx
  hooks/useGetRoomsSocket.ts
  package.json
  style/mainPage/main.module.css
  types/index.ts
  utils/RoomSearch.tsx
  yarn.lock
Labels: ✍️ Refactor, ✨Feature

#291 [Fix #290] - interface 병합 문제 pr
  components/mafia/RemoteParticipant.tsx
  types/index.ts
Labels: 🔨 Fix

#296 [Feat #293] players에게 play 번호 할당
  app/(withGlobalLayout)/main/page.tsx
  components/mafia/LocalParticipant.tsx
  components/mafia/RemoteParticipant.tsx
  components/mafia/RemoteParticipantTile.tsx
  store/game-store.ts
  types/index.ts
Labels: ✨Feature

#298 [Fix #286] 페이지네이션 컴포넌트 삽입
  app/(withGlobalLayout)/ranking/page.tsx
  components/ranking/Pagination.tsx
  package-lock.json
  package.json
Labels: 🔨 Fix

#301 [BugFix #300] 게임 시작 후 초기화 및 player 번호 부여
  components/mafia/LocalParticipant.tsx
  components/mafia/RemoteParticipant.tsx
  components/mafia/RemoteParticipantTile.tsx
  components/mafia/SpeakTimer.tsx
  hooks/useCountDown.ts
  hooks/useModalSocket.ts
  hooks/useSocketOn.ts
  store/game-store.ts
  types/index.ts
  utils/ModalProgress.tsx
  utils/mafiaSocket/getPlayerNumber.ts
  yarn.lock
Labels: 🐞bugFix

#305 [Refactor #292] - 메인페이지 코드 수정, 검색부분 Debounce 적용
  .vscode/settings.json
  app/(withGlobalLayout)/main/page.tsx
  app/(withGlobalLayout)/ranking/page.tsx
  app/favicon.ico
  app/globals.css
  components/layout/Nav.tsx
  components/mafia/JoinMafiaRoom.tsx
  components/main/CreateRoomModal.tsx
  components/main/MainVisual.tsx
  components/main/RoomListItem.tsx
  components/ranking/MyRanking.tsx
  components/ranking/Pagination.tsx
  hooks/useGetRoomsSocket.ts
  hooks/useJoinRoom.ts
  hooks/useJoinRoomSocket.ts
  hooks/useSearchDebounce.ts
  store/connect-store.ts
  style/mainPage/main.module.css
  style/ranking/ranking.module.css
  types/index.ts
  utils/CommonsLoading.tsx
  utils/FormSearch.tsx
  utils/RoomSearch.tsx
  utils/socket/socket.ts
  utils/supabase/authAPI.ts
  yarn.lock
Labels: ✍️ Refactor, ✨Feature, 🔨 Fix

#307 [FIx #297] history API를 사용하여 뒤로가기 구현
  app/(withGlobalLayout)/main/page.tsx
  app/(withoutGlobalLayout)/room/[id]/page.tsx
  components/layout/Loading.tsx
  components/mafia/JoinMafiaRoom.tsx
  components/mafia/LocalParticipant.tsx
  components/mafia/MafiaPlayRooms.tsx
  components/modal/CheckModal.tsx
  hooks/useGetRoomsSocket.ts
  hooks/useMediaSocket.ts
  hooks/useModal.ts
  hooks/useModalSocket.ts
  hooks/usePopStateHandler.ts
  hooks/useSocketOn.ts
  store/exit-store.ts
  types/index.ts
  utils/goBack/goBackHandler.ts
Labels: ✨Feature, 🔨 Fix

#312 [Feat 309] 게임 종료 시 게임 초기화
  components/mafia/GameStartButton.tsx
  components/mafia/LocalParticipant.tsx
  components/mafia/MafiaPlayRooms.tsx
  components/mafia/RemoteParticipant.tsx
  components/mafia/RemoteParticipantTile.tsx
  hooks/useClickHandler.ts
  hooks/useMediaSocket.ts
  hooks/useModalSocket.ts
  hooks/usePlayerNumber.ts
  store/game-store.ts
  store/image-store.ts
  store/overlay-store.ts
  types/index.ts
  utils/mafiaSocket/getPlayerNumber.ts
Labels: ✨Feature

#315 [Feat #311] - 메인페이지 EmailJS추가
  app/(withGlobalLayout)/inquiry/page 2.tsx
  app/(withGlobalLayout)/inquiry/page.tsx
  app/globals.css
  assets/images/icon-github.svg
  components/layout/Footer.tsx
  package-lock.json
  package.json
  style/commons/commons.module.css
  yarn.lock
Labels: ✨Feature

#314 [Feat #306] - 메인페이지 팝업 추가
  app/(withGlobalLayout)/main/page.tsx
  package-lock.json
  package.json
  style/commons/commons.module.css
  utils/Popup.tsx
  yarn.lock
Labels: ✨Feature

#317 [Fix 313] 모달창 겹치는 현상 해결
  components/mafia/LocalParticipant.tsx
  components/mafia/MafiaModals.tsx
  components/mafia/MafiaPlayRooms.tsx
  components/mafia/RemoteParticipantTile.tsx
  hooks/useMediaSocket.ts
  hooks/useModalSocket.ts
  hooks/usePlayerNumber.ts
  store/game-store.ts
  types/index.ts
  utils/ModalProgress.tsx
Labels: 🐞bugFix

#319 [Fix #316] - 메인페이지 useJoinRoom hook 수정
  app/(withGlobalLayout)/main/page.tsx
  components/main/RoomListItem.tsx
  hooks/useJoinRoom.ts
  style/commons/commons.module.css
  types/index.ts
  utils/supabase/authAPI.ts
Labels: 🔨 Fix

#322 [Fix 318] 승리한 팀의 players nickname 표시 및 token 발급 에러 및 미디어 비활성화 처리
  components/mafia/JoinMafiaRoom.tsx
  components/mafia/MafiaModals.tsx
  components/mafia/MafiaPlayRooms.tsx
  components/modal/VictoryModal.tsx
Labels: 🔨 Fix
