Repository ice-craft/ice-craft-FE, pull requests merged in 2024-07, with the labels that each got.

#324 [Fix 323] 입장 시간 동일 시) userId로 정렬하여 playerNumber 부여
  components/mafia/RemoteParticipantTile.tsx
  utils/mafiaSocket/getPlayerNumber.ts
Labels: 🐞bugFix

#326 [Test #325] 최종 테스트 수정 병합 완료
  components/mafia/JoinMafiaRoom.tsx
  hooks/useJoinRoom.ts
  utils/socket/socket.ts
Labels: 🐞bugFix

#329 [Fix 328] 새로고침 및 게임 종료시 초기화
  app/(withoutGlobalLayout)/room/[id]/page.tsx
  components/layout/Loading.tsx
  components/mafia/JoinMafiaRoom.tsx
  components/mafia/MafiaModals.tsx
  components/mafia/MafiaPlayRooms.tsx
  components/main/CreateRoomModal.tsx
  hooks/useJoinRoom.ts
  hooks/useMediaSocket.ts
  store/exit-store.ts
  store/room-store.ts
  tsconfig.json
  types/index.ts
  utils/goBack/goBackHandler.ts
  utils/reload/beforeUnloadHandler.ts
  utils/reload/useBeforeUnloadHandler.ts
  utils/socket/socket.ts
Labels: 🐞bugFix, ✨Feature

#331 [bugFix 330] 게임 종료 시 미디어 초기화
  components/mafia/GameStartButton.tsx
  components/mafia/LocalParticipant.tsx
  components/mafia/MafiaModals.tsx
  components/mafia/MafiaPlayRooms.tsx
  components/mafia/RemoteParticipantTile.tsx
  hooks/useClickHandler.ts
  hooks/useMediaDevice.ts
  hooks/usePlayerNumber.ts
  store/game-store.ts
  types/index.ts
Labels: 🐞bugFix

#332 [Fix #321] - 메인페이지 모달창 리팩토링
  app/(withGlobalLayout)/inquiry/page 2.tsx
  app/(withGlobalLayout)/main/page.tsx
  components/layout/Nav.tsx
  components/mafia/MafiaPlayRooms.tsx
  components/main/CreateRoomModal.tsx
  components/main/RoomListItem.tsx
  hooks/useGetRoomsSocket.ts
  hooks/useJoinRoom.ts
  types/index.ts
  utils/goBack/goBackHandler.ts
  utils/supabase/authAPI.ts
Labels: 🔨 Fix

#302 [Refactor #268] 마피아 게임 서버 및 클라이언트 리팩토링
  app/(withGlobalLayout)/mafia_play/page.tsx
Labels: ✍️ Refactor

#336 [bugFix 334] 모달창 겹치는 현상 및 승리 모달창 에러 해결
  components/mafia/MafiaModals.tsx
  components/mafia/MafiaPlayRooms.tsx
  components/mafia/RemoteParticipant.tsx
  components/modal/VictoryModal.tsx
  hooks/useGetRoomsSocket.ts
  hooks/useMediaDevice.ts
  hooks/usePlayerNumber.ts
  style/modal/modal.module.css
  utils/ModalProgress.tsx
  utils/mafiaSocket/getPlayersNumber.ts
Labels: 🐞bugFix

#337 [Refactor #335] 게임이 끝나고 UI가 초기화 되지 않는 현상 수정
  components/mafia/MafiaPlayRooms.tsx
  hooks/useJoinRoomSocket.ts
  utils/mafiaSocket/getPlayersNumber.ts
  utils/socket/socket.ts
Labels: ✍️ Refactor

#340 [Fix #339] 마피아페이지 코드 정리 및 모달창 progressbar 수정
  api/liveKitApi.ts
  app/(withGlobalLayout)/main/page.tsx
  app/livekit/get-participant-token/route.ts
  components/mafia/GameStartButton.tsx
  components/mafia/JoinMafiaRoom.tsx
  components/mafia/MafiaModals.tsx
  components/mafia/MafiaPlayRooms.tsx
  components/modal/CheckModal.tsx
  components/modal/VictoryModal.tsx
  hooks/useGetRoomsSocket.ts
  hooks/useJoinRoom.ts
  hooks/useJoinRoomSocket.ts
  hooks/useMediaDevice.ts
  hooks/useSearchDebounce.ts
  hooks/useSelectSocket.ts
  hooks/useToken.ts
  middleware.ts
  store/connect-store.ts
  types/index.ts
  utils/FormSearch.tsx
  utils/ModalConfetti.tsx
  utils/reload/useBeforeUnloadHandler.ts
  utils/socket/socket.ts
  utils/supabase/authAPI.ts
Labels: 🐞bugFix

#341 [Fix #333] - 메인페이지 오류들 수정, 타입봇 추가
  app/(withGlobalLayout)/mafia_play/page.tsx
  app/(withGlobalLayout)/main/page.tsx
  app/globals.css
  assets/images/arrow_top.svg
  assets/images/arrow_top_hover.svg
  components/layout/Nav.tsx
  components/mafia/MafiaPlayRooms.tsx
  components/main/CreateRoomModal.tsx
  components/main/RoomListItem.tsx
  components/ranking/Pagination.tsx
  hooks/useGetRooms.ts
  hooks/useGetRoomsSocket.ts
  hooks/useJoinRoom.ts
  hooks/useJoinRoomSocket.ts
  hooks/useSearchDebounce.ts
  hooks/useToken.ts
  hooks/useUserInfo.ts
  package-lock.json
  package.json
  store/count-store.ts
  store/image-store.ts
  store/loading-store.ts
  style/commons/commons.module.css
  style/ranking/ranking.module.css
  types/index.ts
  types/supabase.ts
  utils/FormSearch.tsx
  utils/GoTopButton.tsx
  utils/InfoChat.tsx
  utils/supabase/authAPI.ts
  yarn.lock
Labels: ✍️ Refactor, ✨Feature, 🔨 Fix

#345 [Fix #338] 회원가입 절차 수정
  app/(withGlobalLayout)/chat_client/page.tsx
  app/(withoutGlobalLayout)/login/page.tsx
  app/(withoutGlobalLayout)/register/page.tsx
  app/(withoutGlobalLayout)/sns-login/page.tsx
  app/test/page.tsx
  package.json
  utils/mafia-algorithm/class/citizenClass.js
  utils/mafia-algorithm/class/doctorClass.js
  utils/mafia-algorithm/class/mafiaClass.js
  utils/mafia-algorithm/class/moderatorClass.js
  utils/mafia-algorithm/class/policeClass.js
  utils/mafia-algorithm/gamePlay.js
  utils/mafia-algorithm/play-variable.js
  utils/supabase/accountAPI.ts
  utils/supabase/authAPI.ts
  utils/supabase/roomAPI.ts
  yarn.lock
Labels: 🔨 Fix

#346 [Style #342] - 전체 CSS 점검
  assets/images/1.gif
  assets/images/leader.svg
  assets/images/mafia_day_bg.avif
  assets/images/mafia_night_bg.avif
  assets/images/mafia_room_bg.avif
  assets/images/song_game_title 2.svg
  components/mafia/GameStartButton.tsx
  components/mafia/JoinMafiaRoom.tsx
  components/mafia/LocalParticipant.tsx
  components/mafia/MafiaNickName.tsx
  components/mafia/MafiaPlayRooms.tsx
  components/mafia/RemoteParticipantTile.tsx
  components/mafia/RenderCards.tsx
  components/mafia/SpeakTimer.tsx
  components/modal/UserRoleModal.tsx
  components/ranking/Pagination.tsx
  style/commons/commons.module.css
  style/livekit/livekit.module.css
  style/login/login.module.css
  style/modal/modal.module.css
  style/ranking/ranking.module.css
  style/register/register.module.css
  types/index.ts
  utils/ModalConfetti.tsx
Labels: 🎨 Style

#348 [Style #347] - 마피아 게임 페이지 수정, 메인페이지 수정
  assets/images/mafia_day_bg.avif
  assets/images/mafia_night_bg.avif
  assets/images/mafia_night_bg2.avif
  style/livekit/livekit.module.css
  style/mainPage/main.module.css
  style/mainPage/swiper.css
  utils/Popup.tsx
Labels: 🎨 Style

#352 [Style #350] - 전체페이지 반응형 수정
  app/globals.css
  components/layout/Nav.tsx
  components/main/MainVisual.tsx
  hooks/useJoinRoom.ts
  style/Intropage/intro.module.css
  style/commons/commons.module.css
  style/login/login.module.css
  style/mainPage/main.module.css
  style/mainPage/swiper.css
  style/ranking/ranking.module.css
  style/register/register.module.css
Labels: 🎨 Style

#354 [Style #353] - CSS 반응형 수정
  app/(withGlobalLayout)/layout.tsx
  app/(withGlobalLayout)/mafiainfo/page.tsx
  components/mafia/MafiaModals.tsx
  components/modal/GroupMafiaModal.tsx
  components/modal/LastVoteResultModal.tsx
  components/modal/VoteResultModal.tsx
  store/overlay-store.ts
  store/toggle-store.ts
  style/mafiaInfo/mafiaInfo.module.css
  style/ranking/ranking.module.css
Labels: 🎨 Style

#356 [Fix #343] 마피아 에러 수정(배경화면, 아이콘)
  app/(withGlobalLayout)/main/page.tsx
  app/(withoutGlobalLayout)/login/page.tsx
  app/(withoutGlobalLayout)/page.tsx
  app/(withoutGlobalLayout)/register/page.tsx
  components/layout/Header.tsx
  components/layout/Nav.tsx
  components/mafia/ MafiaHeader.tsx
  components/mafia/GameStartButton.tsx
  components/mafia/JoinMafiaRoom.tsx
  components/mafia/LocalParticipant.tsx
  components/mafia/MafiaPlayRooms.tsx
  components/mafia/RemoteParticipantTile.tsx
  components/mafia/SpeakTimer.tsx
  components/main/CreateRoomModal.tsx
  components/main/MainSkeleton.tsx
  components/main/RoomList.tsx
  components/main/RoomListItem.tsx
  components/modal/VictoryModal.tsx
  hooks/useChief.ts
  hooks/useGetRoomsSocket.ts
  hooks/useJoinRoom.ts
  hooks/useJoinRoomSocket.ts
  hooks/useMediaDevice.ts
  hooks/usePlayerNumber.ts
  store/loading-store.ts
  store/toggle-store.ts
  style/mainPage/main.module.css
  types/index.ts
  utils/CommonsLoading.tsx
  utils/supabase/authAPI.ts
  yarn.lock
Labels: 🐞bugFix

#357 [Fix #355] - 병합 수정 완료
  components/mafia/MafiaHeader.tsx
  components/mafia/MafiaPlayRooms.tsx
  components/mafia/RemoteParticipantTile.tsx
  style/commons/commons.module.css
  style/livekit/livekit.module.css
  utils/socket/socket.ts
Labels: 🐞bugFix

#363 [Feat #351] 랭킹 시스템 구현
  app/(withGlobalLayout)/callback/route.ts
  app/(withGlobalLayout)/ranking/page.tsx
  app/(withoutGlobalLayout)/register/page.tsx
  app/(withoutGlobalLayout)/sns-login/page.tsx
  app/layout.tsx
  app/provider.tsx
  components/layout/Nav.tsx
  components/ranking/MyRanking.tsx
  components/ranking/Pagination.tsx
  types/index.ts
  types/supabase.ts
  utils/FormSearch.tsx
  utils/supabase/accountAPI.ts
  utils/supabase/authAPI.ts
  utils/supabase/rankingAPI.ts
  utils/supabase/roomAPI.ts
Labels: ✨Feature

#364 [Fix #361] - 마피아 게임페이지 밤,낮 배경화면 수정
  components/mafia/MafiaHeader.tsx
Labels: 🐞bugFix

#366 [bugFix #359] 마피아 게임페이지 최종 에러 수정 및 랭킹 산정
  components/mafia/JoinMafiaRoom.tsx
  components/mafia/LocalParticipant.tsx
  components/mafia/MafiaHeader.tsx
  components/mafia/MafiaModals.tsx
  components/mafia/MafiaPlayRooms.tsx
  components/mafia/MafiaToolTip.tsx
  components/mafia/RemoteParticipant.tsx
  components/mafia/RemoteParticipantTile.tsx
  components/mafia/RenderCards.tsx
  components/mafia/SpeakTimer.tsx
  components/modal/CheckModal.tsx
  components/modal/UserRoleModal.tsx
  components/modal/VictoryModal.tsx
  hooks/useBeforeUnloadHandler.ts
  hooks/useChief.ts
  hooks/useClickHandler.ts
  hooks/usePlayerNumber.ts
  hooks/useSelectSocket.ts
  store/game-store.ts
  types/index.ts
  types/supabase.ts
  utils/ModalProgress.tsx
  utils/livekit/liveKitApi.ts
  utils/mafia/getPlayerJob.ts
  utils/mafia/getPlayersNumber.ts
  utils/mafiaSocket/mafiaSocket.ts
  utils/modal/modal.tsx
Labels: 🐞bugFix, ✨Feature

#370 [Fix #365] ios환경 영상 안보이게 수정
  app/(withoutGlobalLayout)/page.tsx
Labels: 🔨 Fix

#371 배포 후 수정 반영 완료
  app/(withoutGlobalLayout)/page.tsx
Labels: 🐞bugFix
