Repository ice-craft/ice-craft-FE, pull requests merged in 2024-08, with the labels that each got.

#373 [Fix #372] - nav 반응형 진입 시 랭킹페이지 이동 수정, 반응형 수정
  components/layout/Nav.tsx
  components/ranking/MyRanking.tsx
  components/ranking/Pagination.tsx
  style/mafiaInfo/mafiaInfo.module.css
  style/ranking/ranking.module.css
  utils/socket/socket.ts
Labels: 🔨 Fix

#375 [bugFix #369] 1차 배포 최종 테스트 및 버그 수정
  app/(withGlobalLayout)/inquiry/page.tsx
  app/layout.tsx
  components/layout/Nav.tsx
  components/mafia/GameStartButton.tsx
  components/mafia/JoinMafiaRoom.tsx
  components/mafia/LocalParticipant.tsx
  components/mafia/MafiaHeader.tsx
  components/mafia/MafiaModals.tsx
  components/mafia/MafiaPlayRooms.tsx
  components/mafia/MafiaToolTip.tsx
  components/mafia/RemoteParticipantTile.tsx
  components/mafia/RenderCards.tsx
  components/mafia/SpeakTimer.tsx
  components/main/CreateRoomModal.tsx
  components/modal/VictoryModal.tsx
  hooks/useBeforeUnloadHandler.ts
  hooks/useClickHandler.ts
  hooks/useCountDown.ts
  hooks/useJoinRoom.ts
  hooks/useMediaDevice.ts
  hooks/usePlayerNumber.ts
  hooks/usePopStateHandler.ts
  hooks/useSocketOn.ts
  store/game-store.ts
  utils/FormSearch.tsx
  utils/goBack/goBackHandler.ts
  utils/participantCamSettings/camSetting.ts
  utils/socket/socket.ts
Labels: 🐞bugFix

#376 테스트 후 배포완료
  app/(withGlobalLayout)/inquiry/page.tsx
  app/layout.tsx
  components/layout/Nav.tsx
  components/mafia/GameStartButton.tsx
  components/mafia/JoinMafiaRoom.tsx
  components/mafia/LocalParticipant.tsx
  components/mafia/MafiaHeader.tsx
  components/mafia/MafiaModals.tsx
  components/mafia/MafiaPlayRooms.tsx
  components/mafia/MafiaToolTip.tsx
  components/mafia/RemoteParticipantTile.tsx
  components/mafia/RenderCards.tsx
  components/mafia/SpeakTimer.tsx
  components/main/CreateRoomModal.tsx
  components/modal/VictoryModal.tsx
  components/ranking/MyRanking.tsx
  components/ranking/Pagination.tsx
  hooks/useBeforeUnloadHandler.ts
  hooks/useClickHandler.ts
  hooks/useCountDown.ts
  hooks/useJoinRoom.ts
  hooks/useMediaDevice.ts
  hooks/usePlayerNumber.ts
  hooks/usePopStateHandler.ts
  hooks/useSocketOn.ts
  store/game-store.ts
  style/mafiaInfo/mafiaInfo.module.css
  style/ranking/ranking.module.css
  utils/FormSearch.tsx
  utils/goBack/goBackHandler.ts
  utils/participantCamSettings/camSetting.ts
  utils/socket/socket.ts
Labels: 🌏 Deploy

#377 [Fix #374] - 랭킹페이지 반응형 진입 시 word 깨지는 현상 수정
  components/mafia/MafiaPlayRooms.tsx
  style/modal/modal.module.css
  style/ranking/ranking.module.css
Labels: 🎨 Style

#378 테스트 후 메인브랜치로 배포
  components/mafia/MafiaPlayRooms.tsx
  style/modal/modal.module.css
  style/ranking/ranking.module.css
Labels: 🌏 Deploy

#381 [bugFix #380] 입장하기, 실시간 방 변경, 방만들기 에러 수정
  README.md
  app/(withGlobalLayout)/main/page.tsx
  components/mafia/MafiaHeader.tsx
  components/main/CreateRoomModal.tsx
  components/main/MainCreateRoom.tsx
  hooks/useJoinRoom.ts
  hooks/useJoinRoomSocket.ts
  store/game-store.ts
  store/toggle-store.ts
Labels: 🐞bugFix, 🔨 Fix

#385 [Fix #367] 메타데이터 삽입
  .vscode/settings.json
  app/(withGlobalLayout)/mafiainfo/page.tsx
  app/(withGlobalLayout)/ranking/page.tsx
  app/(withoutGlobalLayout)/page.tsx
  components/mafia/MafiaPlayRooms.tsx
Labels: 🔨 Fix

#386 [Fix #379] - 테스트 후 배포 전 console.log 삭제
  README.md
  app/(withGlobalLayout)/main/page.tsx
  components/mafia/MafiaPlayRooms.tsx
Labels: 🌏 Deploy

#387 테스트 후 메인브랜치로 배포 완료
  .vscode/settings.json
  README.md
  app/(withGlobalLayout)/mafiainfo/page.tsx
  app/(withGlobalLayout)/main/page.tsx
  app/(withGlobalLayout)/ranking/page.tsx
  app/(withoutGlobalLayout)/page.tsx
  components/mafia/MafiaHeader.tsx
  components/mafia/MafiaPlayRooms.tsx
  components/main/CreateRoomModal.tsx
  components/main/MainCreateRoom.tsx
  hooks/useJoinRoom.ts
  hooks/useJoinRoomSocket.ts
  store/game-store.ts
  store/toggle-store.ts
Labels: 🌏 Deploy

#390 [Feat #389] - 구글 애널리틱스 추가, 스켈레톤 ui 반응형 수정
  README.md
  app/layout.tsx
  package-lock.json
  package.json
  style/mainpage/main.module.css
  utils/GoogleTracker.tsx
  yarn.lock
Labels: ✨Feature

#391 메인브랜치로 병합 완료
  app/layout.tsx
  package-lock.json
  package.json
  style/mainpage/main.module.css
  utils/GoogleTracker.tsx
  yarn.lock
Labels: 🌏 Deploy

#394 메인브랜치로 배포 병합 완료
  app/(withGlobalLayout)/main/page.tsx
  components/layout/Loading.tsx
  yarn.lock
Labels: 🌏 Deploy

#398 [Feat #396] - 마피아 설명 페이지 애니메이션 추가, 배포 후 수정 작업
  app/(withGlobalLayout)/mafiainfo/page.tsx
  app/(withGlobalLayout)/ranking/page.tsx
  app/(withoutGlobalLayout)/login/page.tsx
  app/(withoutGlobalLayout)/page.tsx
  app/(withoutGlobalLayout)/register/page.tsx
  app/layout.tsx
  assets/images/citizen_victory.svg
  assets/images/mafia_info_final.svg
  assets/images/mafia_info_morning.svg
  assets/images/mafia_info_vote.svg
  assets/images/mafia_victory.svg
  components/mafiaInfo/InfoItem.tsx
  components/mafiaInfo/InfoTitle.tsx
  package-lock.json
  package.json
  style/mafiaInfo/mafiaInfo.module.css
  style/mainpage/swiper.css
  types/index.ts
  utils/supabase/authAPI.ts
  yarn.lock
Labels: ✨Feature, 🔨 Fix

#399 [bugFix #397] 뒤로가기 수정
  app/(withoutGlobalLayout)/login/page.tsx
  app/(withoutGlobalLayout)/register/page.tsx
  components/layout/Loading.tsx
  components/mafia/JoinMafiaRoom.tsx
  store/room-store.ts
  types/index.ts
  yarn.lock
Labels: 🐞bugFix

#400 메인브랜치로 병합 완료
  app/(withGlobalLayout)/mafiainfo/page.tsx
  app/(withGlobalLayout)/ranking/page.tsx
  app/(withoutGlobalLayout)/login/page.tsx
  app/(withoutGlobalLayout)/page.tsx
  app/(withoutGlobalLayout)/register/page.tsx
  app/layout.tsx
  assets/images/citizen_victory.svg
  assets/images/mafia_info_final.svg
  assets/images/mafia_info_morning.svg
  assets/images/mafia_info_vote.svg
  assets/images/mafia_victory.svg
  components/layout/Loading.tsx
  components/mafia/JoinMafiaRoom.tsx
  components/mafiaInfo/InfoItem.tsx
  components/mafiaInfo/InfoTitle.tsx
  package-lock.json
  package.json
  store/room-store.ts
  style/mafiaInfo/mafiaInfo.module.css
  style/mainpage/swiper.css
  types/index.ts
  utils/supabase/authAPI.ts
  yarn.lock
Labels: 🌏 Deploy

#403 [Style #401] - 배포 테스트 후 반응형 진입 시 모바일 수정
  assets/images/song_game_title.svg
  style/mafiaInfo/mafiaInfo.module.css
  style/mainpage/swiper.css
Labels: 🎨 Style

#404 배포 브랜치로 병합 완료
  assets/images/song_game_title.svg
  style/mafiaInfo/mafiaInfo.module.css
  style/mainpage/swiper.css
Labels: 🌏 Deploy

#406 [Style #405] - 배포 후 CSS 반응형 수정 완료
  app/(withoutGlobalLayout)/login/page.tsx
  app/(withoutGlobalLayout)/register/page.tsx
  app/layout.tsx
  components/mafiaInfo/InfoItem.tsx
  components/main/CreateRoomModal.tsx
  components/main/MainCreateRoom.tsx
  hooks/useJoinRoom.ts
  style/livekit/livekit.module.css
  style/mafiaInfo/mafiaInfo.module.css
  style/mainpage/main.module.css
  style/mainpage/swiper.css
  style/modal/modal.module.css
  types/index.ts
Labels: 🎨 Style

#407 메인브랜치로 병합 완료
  app/(withoutGlobalLayout)/login/page.tsx
  app/(withoutGlobalLayout)/register/page.tsx
  app/layout.tsx
  components/mafiaInfo/InfoItem.tsx
  components/main/CreateRoomModal.tsx
  components/main/MainCreateRoom.tsx
  hooks/useJoinRoom.ts
  style/livekit/livekit.module.css
  style/mafiaInfo/mafiaInfo.module.css
  style/mainpage/main.module.css
  style/mainpage/swiper.css
  style/modal/modal.module.css
  types/index.ts
Labels: 🌏 Deploy

#410 [bugFix #409] 로그인 페이지 쿠키 및 key 경고 해결
  app/(withGlobalLayout)/ranking/page.tsx
  app/(withoutGlobalLayout)/login/page.tsx
  app/(withoutGlobalLayout)/page.tsx
  app/(withoutGlobalLayout)/register/page.tsx
  app/layout.tsx
  components/logIn/ErrorMessage.tsx
  utils/supabase/authAPI.ts
Labels: 🐞bugFix

#411 [Feat #402] 점검
  app/(withoutGlobalLayout)/page.tsx
  app/(withoutGlobalLayout)/sns-login/page.tsx
  assets/images/media_error.svg
  components/layout/Nav.tsx
  components/mafia/JoinMafiaRoom.tsx
  components/mafia/MafiaHeader.tsx
  components/ranking/MyRanking.tsx
  style/commons/commons.module.css
  style/livekit/livekit.module.css
  utils/Popup.tsx
  utils/supabase/authAPI.ts
Labels: ✨Feature, 🔨 Fix

#412 메인브랜치로 병합 완료
  app/(withGlobalLayout)/ranking/page.tsx
  app/(withoutGlobalLayout)/login/page.tsx
  app/(withoutGlobalLayout)/page.tsx
  app/(withoutGlobalLayout)/register/page.tsx
  app/(withoutGlobalLayout)/sns-login/page.tsx
  app/layout.tsx
  assets/images/media_error.svg
  components/layout/Nav.tsx
  components/logIn/ErrorMessage.tsx
  components/mafia/JoinMafiaRoom.tsx
  components/mafia/MafiaHeader.tsx
  components/ranking/MyRanking.tsx
  style/commons/commons.module.css
  style/livekit/livekit.module.css
  utils/Popup.tsx
  utils/supabase/authAPI.ts
Labels: 🌏 Deploy

#414 [Style #413] - 배포 후 테스트 점검 CSS 수정, 메인페이지 게임 list playing중 UI수정
  app/not-found.tsx
  assets/images/error_page.avif
  assets/images/media_error.svg
  assets/images/sorry_image.avif
  components/layout/Loading.tsx
  components/mafia/JoinMafiaRoom.tsx
  components/main/RoomListItem.tsx
  style/commons/commons.module.css
  style/livekit/livekit.module.css
Labels: 🎨 Style

#415 메인브랜치로 병합 완료
  app/not-found.tsx
  assets/images/error_page.avif
  assets/images/media_error.svg
  assets/images/sorry_image.avif
  components/layout/Loading.tsx
  components/mafia/JoinMafiaRoom.tsx
  components/main/RoomListItem.tsx
  style/commons/commons.module.css
  style/livekit/livekit.module.css
Labels: 🌏 Deploy

#418 [Style #416] - 배포 후 마피아 게임 페이지 CSS수정, goTopButton위치 수정
  app/globals.css
  style/commons/commons.module.css
Labels: 🎨 Style

#419 [Test #417] 로그인 및 메인페이지 CreateModal JoinRoom socket 중복 제거
  app/(withGlobalLayout)/ranking/page.tsx
  app/(withoutGlobalLayout)/page.tsx
  components/layout/Footer.tsx
  components/layout/Header.tsx
  components/layout/Nav.tsx
  components/main/CreateRoomModal.tsx
  components/main/MainCreateRoom.tsx
  components/ranking/MyRanking.tsx
  hooks/useJoinRoom.ts
  tsconfig.json
  utils/GoTopButton.tsx
  utils/supabase/authAPI.ts
Labels: 🔨 Fix

#420 메인브랜치로 병합 완료
  app/(withGlobalLayout)/ranking/page.tsx
  app/(withoutGlobalLayout)/page.tsx
  app/globals.css
  components/layout/Footer.tsx
  components/layout/Header.tsx
  components/layout/Nav.tsx
  components/main/CreateRoomModal.tsx
  components/main/MainCreateRoom.tsx
  components/ranking/MyRanking.tsx
  hooks/useJoinRoom.ts
  style/commons/commons.module.css
  tsconfig.json
  utils/GoTopButton.tsx
  utils/supabase/authAPI.ts
Labels: 🌏 Deploy

#422 [bugFix #421] 방 입장 에러 확인
  components/mafia/JoinMafiaRoom.tsx
Labels: 🐞bugFix

#424 배포 브랜치로 병합 완료
  components/mafia/JoinMafiaRoom.tsx
Labels: 🌏 Deploy

#427 [Fix #426] - 피드백 반영 CSS 수정, 인트로페이지 영상 url 변경작업
  .github/workflows/deploy.yml
  README.md
  app/(withoutGlobalLayout)/page.tsx
  assets/images/visit_empty.svg
  build.sh
  components/mafia/JoinMafiaRoom.tsx
  package-lock.json
  style/commons/commons.module.css
  style/mainpage/main.module.css
  yarn.lock
Labels: 🎨 Style, 🔨 Fix

#429 [bugfix #425] 방 입장 후 미디어 장치 접근 제한 설정
  components/mafia/JoinMafiaRoom.tsx
  components/mafia/MafiaHeader.tsx
  components/mafia/MafiaModals.tsx
  components/mafia/MafiaPlayRooms.tsx
  utils/socket/socket.ts
Labels: 🐞bugFix

#430 메인브랜치로 병합 완료
  app/(withoutGlobalLayout)/page.tsx
  assets/images/visit_empty.svg
  components/mafia/JoinMafiaRoom.tsx
  components/mafia/MafiaHeader.tsx
  components/mafia/MafiaModals.tsx
  components/mafia/MafiaPlayRooms.tsx
  package-lock.json
  style/commons/commons.module.css
  style/mainpage/main.module.css
  utils/socket/socket.ts
  yarn.lock
Labels: 🌏 Deploy

#432 [Fix 431] 배포 서버로 변경
  utils/socket/socket.ts
Labels: 🔨 Fix

#433 메인브랜치로 병합 완료
  utils/socket/socket.ts
Labels: 🌏 Deploy

#435 [Style #434] - 메인페이지 Search CSS 수정
  assets/images/search_empty.svg
  assets/images/visit_empty.svg
  style/mainpage/main.module.css
Labels: 🎨 Style

#436 메인브랜치로 병합 완료
  assets/images/search_empty.svg
  assets/images/visit_empty.svg
  style/mainpage/main.module.css
Labels: 🌏 Deploy
