Repository ice-craft/ice-craft-FE, pull requests merged in 2024-05, with the labels that each got.

#233 indicator 기능 추가
  components/mafia/JoinMafiaRoom.tsx
  components/mafia/LocalParticipant.tsx
  components/mafia/MafiaPlayRooms.tsx
  utils/mafiaSocket/mafiaSocket.ts
  utils/participantCamSettings/camSetting.ts
  utils/socket/socket.ts
Labels: ✨Feature

#236 [Fix #235] 마피아 게임 구조 변경
  app/(withGlobalLayout)/mafia_play/page.tsx
  utils/socket/socket.ts
Labels: 🔨 Fix

#242 코드 정리 및 미디어 장치 기능(미완성)
  components/mafia/GameStartButton.tsx
  components/mafia/JoinMafiaRoom.tsx
  components/mafia/MafiaPlayRooms.tsx
  components/modal/CheckModal.tsx
  hooks/useCountDown.ts
  hooks/useMediaSocket.ts
  hooks/useMediaStatus.ts
  hooks/useShowModalSocket.ts
  hooks/useSocket.ts
  hooks/useSocketOff.ts
  hooks/useSocketOn.ts
  store/showModal.store.ts
  types/index.ts
  utils/mafiaSocket/mafiaSocket.ts
  utils/participantCamSettings/camSetting.ts
Labels: ✨Feature, 🔨 Fix

#245 [Feat#240] - 마피아게임페이지 최종투표 결과값 모달 추가
  app/layout.tsx
  components/modal/VoteResultModal.tsx
  store/showModal.store.ts
  style/modal/modal.module.css
  types/index.ts
Labels: ✨Feature

#248 socket Event 로직 변경 및 전역상태관리 로직 변경
  components/mafia/LocalParticipant.tsx
  components/mafia/MafiaPlayRooms.tsx
  components/modal/CheckModal.tsx
  components/modal/GroupMafiaModal.tsx
  components/modal/VoteResultModal.tsx
  hooks/useCountDown.ts
  hooks/useShowModalSocket.ts
  hooks/useSocketOff.ts
  hooks/useSocketOn.ts
  store/show-Modal-store.ts
  store/showModal.store.ts
  types/index.ts
Labels: ✨Feature, 🔨 Fix

#253 직업 부여 및 직업 아이콘 기능 추가
  components/mafia/LocalParticipant.tsx
  components/mafia/MafiaPlayRooms.tsx
  components/mafia/MafiaToolTip.tsx
  components/mafia/RenderCards.tsx
  components/modal/CheckModal.tsx
  components/modal/GroupMafiaModal.tsx
  components/modal/UserRoleModal.tsx
  components/modal/VoteResultModal.tsx
  hooks/useCountUp.ts
  hooks/useMediaSocket.ts
  hooks/useMediaStatus.ts
  hooks/useModalSocket.ts
  hooks/useShowModalSocket.ts
  hooks/useSocketOff.ts
  hooks/useSocketOn.ts
  store/show-modal-store.ts
  types/index.ts
Labels: 🔨 Fix

#255 [Style #250] 마피아 게임페이지 모달 CSS 수정, 추가
  app/globals.css
  assets/images/modal_bg.svg
  components/modal/CheckModal.tsx
  components/modal/CreateRoomModal.tsx
  components/modal/UserRoleModal.tsx
  style/commons/commons.module.css
  style/livekit/livekit.module.css
  style/modal/modal.module.css
  style/ranking/ranking.module.css
  utils/GoTopButton.tsx
Labels: 🎨 Style

#257 타이머 기능 추가
  components/mafia/LocalParticipant.tsx
  components/mafia/MafiaPlayRooms.tsx
  components/mafia/SpeakTimer.tsx
  components/modal/CheckModal.tsx
  components/modal/GroupMafiaModal.tsx
  components/modal/UserRoleModal.tsx
  components/modal/VoteResultModal.tsx
  hooks/useCountDown.ts
  hooks/useModal.ts
  hooks/useModalSocket.ts
  style/modal/modal.module.css
  utils/GoTopButton.tsx
Labels: ✨Feature, 🔨 Fix
